---
title: "git_00"
author: "Genevieve Metcalf"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son! 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

From childhood’s hour I have not been  
As others were—I have not seen  
As others saw—I could not bring  
My passions from a common spring—  
From the same source I have not taken  
My sorrow—I could not awaken  
My heart to joy at the same tone—  
And all I lov’d—I lov’d alone—  
Then—in my childhood—in the dawn  
Of a most stormy life—was drawn  
From ev’ry depth of good and ill  
The mystery which binds me still—  
From the torrent, or the fountain—  
From the red cliff of the mountain—  
From the sun that ’round me roll’d  
In its autumn tint of gold—  
From the lightning in the sky  
As it pass’d me flying by—  
From the thunder, and the storm—  
And the cloud that took the form  
(When the rest of Heaven was blue)  